### ISSUE TITLE
Why this doesn't throw an exception? it is on IO thread, not Main

### ISSUE THREAD

**Issue by dsdmsa** [mitchtabian/Kotlin-Coroutine-Examples#9]
https://github.com/mitchtabian/Kotlin-Coroutine-Examples/blob/5c5077f93c477d915947ee51192db63aee1a0fd3/app/src/main/java/com/codingwithmitch/coroutineexamples/MainActivity.kt#L74

**Comment by asthagarg2428** [comment]
if you will go to setProgress() of ProgressBar which internally calls refreshProgress() method, it has handling of it being called from Thread other than UIThread also it's synchronised.

**Comment by asthagarg2428** [comment]
> https://github.com/mitchtabian/Kotlin-Coroutine-Examples/blob/5c5077f93c477d915947ee51192db63aee1a0fd3/app/src/main/java/com/codingwithmitch/coroutineexamples/MainActivity.kt#L74
if you will go to setProgress() of ProgressBar which internally calls refreshProgress() method, it has handling of it being called from Thread other than UIThread also it's synchronised.

**Comment by walterkivindu** [comment]
The app crashes with error as shown below

021-05-31 10:30:16.516 16216-16216/? E/routineexample: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2021-05-31 10:30:16.518 16216-16216/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingwithmitch.coroutineexamples, PID: 16216
    java.lang.VerifyError: Verifier rejected class com.codingwithmitch.coroutineexamples.MainActivity: java.lang.Object com.codingwithmitch.coroutineexamples.MainActivity.setTextOnMainThread(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.codingwithmitch.coroutineexamples.MainActivity.setTextOnMainThread(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'com.codingwithmitch.coroutineexamples.MainActivity' appears in /data/app/com.codingwithmitch.coroutineexamples-YyRzacfNGYX1VBJFsSytow==/base.apk!classes3.dex)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
